sudo: false
language: php
php:
- '7.0'
- nightly
before_install:
- phpenv config-rm xdebug.ini
- composer config --global github-oauth.github.com $GITHUB_TOKEN
install: composer install --no-interaction
script: make ci
after_script: bash <(curl -s https://codecov.io/bash)
env:
  global:
    secure: bGBzw+mOfhC/3/VY5+okKwOD8FfliC1JQ/9JiR8ZYk0YxeuSAwj8u8Bm++NbtKe41rANCrd5GztYpTlZb3R3/7tbbD3PlREsrh0X6qZckiRTvgJ8hT2kpBl4J1IDrLFG+MyBD6VGAC4oPtR0yRz4oe0vjSHyduycBahHaWLe6Pw=
