sudo: false
language: php
php: '7.0'
before_install:
- phpenv config-rm xdebug.ini
- composer config --global github-oauth.github.com $GITHUB_TOKEN
install: composer install --no-interaction
script: make ci -j 50
after_script: bash <(curl -s https://codecov.io/bash)
env:
  global:
    secure: g0uexghpfxjO1pVYCBqj/P957zCZQT1v5naWgzDtu5n2Sh1WoW00K4+jOYJ4bbIm+1O8wbzzlyOuYZMMz0xXLVzuOdoMwMhfcnI+pE/dpa4J/vs1RFqoLh4HuNx9oPErNODdmWIkeC1SpcuBeYZfYxEL6UJIWbZZq3a9BIslx88=
notifications:
  slack:
    secure: cSaEpMTscvJmBoKzbjj/emqsyAsrHq+IdQBhbuE403tREik3E++IDeUfh5sVBGJv4hS5AWOKxM/b5Y447r/QN7BdQHZncZWW2Qlrwg1jh39vgQDz2f4sTniO300YkwExnkK3w3Q3DLuS3s6+EcEyWAaj+JBvgsoPx3kQt9eVZiI=
