sudo: false
language: php
php:
- '7.0'
- '7.1'
- '7.2'
- nightly
matrix:
  fast_finish: true
  allow_failures:
  - php: nightly
before_install:
- phpenv config-rm xdebug.ini || true
- "[[ $GITHUB_TOKEN ]] && composer config --global github-oauth.github.com $GITHUB_TOKEN"
install: composer install --no-interaction
script: make ci
after_script: bash <(curl -s https://codecov.io/bash)
env:
  global:
    - RECOIL_INSTRUMENTATION=none
    - secure: dCCJezYz/qPO+jZkqN78wavz7oRWXIAERvgwBxmKtSo6at0/pgeW/RrSnewM1RBOeYFCwxWI7YVrfu+OGgdSIvFYLvHU6ZHKMeGus02MmqkjIzi+kz4kB8gnjPSQeHkWxS/QsvZ5P8UcspZs+FAGStQXXPEsJumf7bPWJKeQ1/U=
cache:
  directories:
  - $HOME/.composer/cache
